### ISSUE TITLE
Trex check cannot handle local alias

### ISSUE THREAD

**Issue by bodograumann** [crewdevio/Trex#111]
I have an alias in my import map:
```
{
  "imports": {
    "@common/": "../common/",
    "std/": "https://deno.land/std@0.105.0/"
  }
}

```

When I run `trex check` it fails with:
```
error: Uncaught (in promise) TypeError: Invalid URL
const toURL = (url: string) => new URL(url);
                               ^
    at Object.opSync (deno:core/01_core.js:142:12)
    at opUrlParse (deno:ext/url/00_url.js:47:27)
    at new URL (deno:ext/url/00_url.js:320:20)
    at toURL (https://deno.land/x/trex@v1.10.0/handlers/handler_check.ts:144:32)
    at isDenoLand (https://deno.land/x/trex@v1.10.0/handlers/handler_check.ts:157:24)
    at checkDepsUpdates (https://deno.land/x/trex@v1.10.0/handlers/handler_check.ts:44:9)
    at async Main (https://deno.land/x/trex@v1.10.0/cli.ts:274:7)
    at async https://deno.land/x/trex@v1.10.0/cli.ts:299:3
```

Instead it should just ignore the local mappings.

**Desktop:**

- OS: Arch Linux
- Deno version: 1.16.1
- Trex Version: 1.10.0

**Comment by buttercubz** [comment]
fixed on #113

**Comment by buttercubz** [comment]
> Are you planning on releasing a new version?

@bodograumann already shipped https://deno.land/x/trex@v1.11.0

**Comment by bodograumann** [comment]
I still get the same error :-/
