### ISSUE TITLE
install error with deno-1.6.2

### ISSUE THREAD

**Issue by transtone** [crewdevio/Trex#77]
when run `deno install -A --unstable -n trex https://deno.land/x/trex/cli.ts`
got: 

```bash
Download https://denopkg.com/crewdevio/Trex@proxy/proxy/files/fmt.ts
Download https://raw.githubusercontent.com/crewdevio/Trex/proxy/proxy/proxy.ts
Download https://denopkg.com/crewdevio/Trex@proxy/proxy/files/encoding.ts
Download https://raw.githubusercontent.com/crewdevio/Trex/proxy/proxy/files/encoding.ts
Download https://raw.githubusercontent.com/crewdevio/Trex/proxy/proxy/files/fmt.ts
Check https://deno.land/x/trex/cli.ts
error: TS2498 [ERROR]: Module '"deno:///none.d.ts"' uses 'export =' and cannot be used with 'export *'.
export * from "https://denopkg.com/crewdevio/Trex@proxy/proxy/files/fmt.ts";
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/imports/fmt.ts:1:15

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/tools/did_you_mean.ts:9:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/utils/info.ts:9:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/utils/logs.ts:12:10

TS2498 [ERROR]: Module '"deno:///none.d.ts"' uses 'export =' and cannot be used with 'export *'.
export * from "https://raw.githubusercontent.com/crewdevio/Trex/proxy/proxy/proxy.ts";
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/imports/proxy.ts:1:15

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'needProxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
         ~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/tools/logs.ts:11:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'Proxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
                    ~~~~~
    at https://deno.land/x/trex@v1.4.0/tools/logs.ts:11:21

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/tools/logs.ts:14:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_files.ts:13:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'needProxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
         ~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_third_party_package.ts:10:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'Proxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
                    ~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_third_party_package.ts:10:21

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'needProxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
         ~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_cache.ts:9:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'Proxy'.
import { needProxy, Proxy } from "../imports/proxy.ts";
                    ~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_cache.ts:9:21

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_cache.ts:12:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/handle_packages.ts:20:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/delete_package.ts:12:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'Proxy'.
import { Proxy, needProxy } from "../imports/proxy.ts";
         ~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/purge_package.ts:10:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/proxy.ts"' has no exported member 'needProxy'.
import { Proxy, needProxy } from "../imports/proxy.ts";
                ~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/purge_package.ts:10:17

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/handlers/purge_package.ts:14:10

TS2498 [ERROR]: Module '"deno:///none.d.ts"' uses 'export =' and cannot be used with 'export *'.
export * from "https://denopkg.com/crewdevio/Trex@proxy/proxy/files/encoding.ts";
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/trex@v1.4.0/imports/encoding.ts:1:15

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/encoding.ts"' has no exported member 'yaml'.
import { yaml } from "../imports/encoding.ts";
         ~~~~
    at https://deno.land/x/trex@v1.4.0/tools/parseToyaml.ts:9:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/commands/run.ts:12:10

TS2305 [ERROR]: Module '"https://deno.land/x/trex@v1.4.0/imports/fmt.ts"' has no exported member 'colors'.
import { colors } from "../imports/fmt.ts";
         ~~~~~~
    at https://deno.land/x/trex@v1.4.0/tools/setup_ide.ts:12:10

Found 23 errors.
              
```

**Comment by RivierGrullon** [comment]
I tried to reproduce the same issue but the error does not happend in my machine, could you be more especific about your OS system pls? Linux or windows?

try to clean all the dependencies of deno and download again. 

Meanwhile i will try to reproduce the issue :)

**Comment by transtone** [comment]
windows 10 20H2 19042.685

and 

wsl gentoo-linux
